### ISSUE TITLE
Throw exceptions when grid zones are too few

### ISSUE THREAD

**Issue by mchandra** [shankar1729/qimpy#33]
Simulation fails for the attached (bad) grid when `grid_spacing = 2` but works when `grid_spacing = 1`. Maybe we can throw an exception when the grid zones in a certain patch are too few.
![gt10-v17](https://github.com/shankar1729/qimpy/assets/527239/5e5b7ff0-8b6a-461b-8575-b72433bf239d)
Input file:
```
fermi_circle:
  kF: 1
  vF: 1
  tau-p: .inf
  tau-ee: .inf
  N-theta: 64

patch_set:
  svg_file: gt10-v18.svg
  grid_spacing: 2.0

  contacts:
    source:
      dmu: +0.1
    drain:
      dmu: -0.1

time_evolution:
  t_max: 1000
  dt_save: 5
  n_collate: 32

checkpoint_out: animation-gt10/advect_{:04d}.h5
```
